server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_system?useSSL=false
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-software
mybatis:
  type-aliases-package: com.gm.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#logging:
#  level:
#    cn.itcast: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka